### ISSUE TITLE
"geeknote: command not found" error with pyenv

### ISSUE THREAD

**Issue by stephenwithav** [avendael/emacs-geeknote#1]
I configured `geeknote-command` with:

```
(setq geeknote-command "/home/steven/repos/.pyenv/versions/2.7/bin/python /home/steven/repos/.pyenv/versions/2.7/bin/geeknote")                                                                                             
```

..and `geeknote-find` returns the command not found error.

Is there a workaround?

**Comment by avendael** [comment]
I would suggest _not_ using a virtual environment and installing geeknote through `pip install --user geeknote` or `python setup.py install --user` in the geeknote directory, and then add the python bin directory to your `PATH`. This way, you don't have to specify the python to execute geeknote.

**Comment by stephenwithav** [comment]
`python` in my repos is 2.6.6, so geeknote won't install.  (`pip install geeknote` fails with `Could not find any downloads that satisfy the requirement geeknote`.)

**Comment by avendael** [comment]
Geeknote, for some reason, is not in the python repos. You'll have to `python setup.py install --user` inside the geeknote project directory after you clone it.

**Comment by stephenwithav** [comment]
A simple change has it working.  Would you prefer a pull request or just paste the change here?

**Comment by avendael** [comment]
A pull request would be cool :)

**Comment by stephenwithav** [comment]
Submitted. :)

`geeknote find` works fine from the CLI and emacs, but creating notes is failing in both places.  I'm considering porting it to Go, which will allow me to avoid virtual environments altogether.

**Comment by avendael** [comment]
I experienced the same problem before, when I used geeknote `HEAD`. There might be some bugs in the current `HEAD`, which is why I'm still using geeknote at `192a0c5`. Maybe I should add this to the readme?

I'll be happy to use a different backend if it works better than geeknote ;) Right now, I'm looking into helm integration.

**Comment by stephenwithav** [comment]
Please do add that note in the `README`; it would have saved me some grief. :)

You go ahead and work on helm integration.  I'm going to work on parsing titles to include the destination notebook and tags.

**Comment by avendael** [comment]
Updated readme. I'll make a release tonight. Thank you for your inputs and for the PRs :+1:
