### ISSUE TITLE
emacsclient in Emacs For Mac OS X

### ISSUE THREAD

**Issue by cas2void** [avendael/emacs-geeknote#4]
It maybe not relevant here, but after googling for a long time, I still can't find the right solution.

Emacs24.5 was installed from macport on Mac OS X 10.10, Emacs daemon is started with
/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs --daemon

then try to edit a note, there is an error says:
emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".

**Comment by avendael** [comment]
Make sure your emacsclient is coming from /Applications/MacPorts/Emacs.app. There's a default emacsclient installed in OSX, and that emacsclient expects the default OSX emacs daemon. If you're using the emacsdaemon from MacPorts, you should use its accompanying emacsclient. You might need to edit your `$PATH`.

**Comment by cas2void** [comment]
Yes, that's the problem. After
$ geeknote settings --editor /Applications/MacPorts/Emacs.app/Contents/MacOS/bin/emacsclient
 it works now. Thank you!

**Comment by avendael** [comment]
You're welcome!
