### ISSUE TITLE
Manage notes the `ranger` style?

### ISSUE THREAD

**Issue by biocyberman** [avendael/emacs-geeknote#7]
First of all, I think this should be implemented in `geeknote` to for broader audience. However, would it be possible to walk note tree and edit notes like `ranger` command-line file manager?

Essentially it will be very cool to do like this:
- List notebooks/stacks
- Jump to the output buffer
- Hit `l` (lowercase of L) for goto sub item
- Hit `j` goto item below
- Hit `k` goto item above. Or go up one level if it is the topmost one already.
- Hit `h` go up one level (parent item)
- Some other editing commands: create item of the same level, edit item, delete item, move item, etc.

**Comment by ayman** [comment]
I made a rather bare bones effort here, not using `ranger` but just lightweight built in navigation tools. 
![image](https://cloud.githubusercontent.com/assets/1846/16403314/b0d563e4-3ca8-11e6-9dd4-c3fb97e05cf7.png)
Here's a simple listing of notebooks for example.  Will polish off and submit a pull request.

**Comment by ayman** [comment]
Pull request #8 adds the interactivity in the buffers as pictured here.

**Comment by avendael** [comment]
Awesome! I'll be looking at the PR soon.

**Comment by avendael** [comment]
Merged Pull request #8
